spring:
  datasource:
    url: jdbc:h2:mem:ged_test_db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  flyway:
    enabled: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

jwt:
  secret: test-secret-key-test-secret-key-123456
  expiration: 3600000

minio:
  enabled: false